@CostCraft.Api_HostAddress = https://localhost:7287
@UserId = 3c9b1834-d977-4f2c-b647-ab28b5992f43
@Token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzYzliMTgzNC1kOTc3LTRmMmMtYjY0Ny1hYjI4YjU5OTJmNDMiLCJ1bmlxdWVfbmFtZSI6Im1yLXNlcmdpdG8iLCJqdGkiOiJiZDYyZjE4Mi1lMTdlLTQ2MGQtOGY5My1lZThiNDE4YmI2MWMiLCJleHAiOjE3MzYxOTgwNjIsImlzcyI6IkNvc3RDcmFmdCIsImF1ZCI6IkNvc3RDcmFmdCJ9.5zYjzX_a7peYVhX3TEIUjnkEQ4XC2-3jnXwcL_G9BVc

POST {{CostCraft.Api_HostAddress}}/users/{{UserId}}/products
Content-Type: application/json
Authorization: Bearer {{Token}}

{
  	"name": "Cake",
	"unitsProduced": 1,
	"profitMarginPercentage": 200,
	"materials": [
		{
			"name": "Flour",
			"purchasedAmount": 1,
			"purchasedUnit": "Kilogram",
			"purchasedPrice": 2.00,
			"usedAmount": 0.25,
			"usedUnit": "Kilogram",
			"usedCost": 0.50
		}
	],
	"labors": [
		{
			"timeUnit": "Hour",
			"timePayRate": 10.00,
			"timeWorked": 2,
			"timeCost": 20.00
		}
	]
}

###
