@CostCraft.Api_HostAddress = https://localhost:7287
@UserId = d591c1d1-85dd-4a5e-9723-cc99d06863a5
@Token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkNTkxYzFkMS04NWRkLTRhNWUtOTcyMy1jYzk5ZDA2ODYzYTUiLCJ1bmlxdWVfbmFtZSI6Im1yLXNlcmdpdG8iLCJqdGkiOiIzNjA0YzkzZi0xZGZjLTRiNjUtOGIyZC03Y2IxMjRjYTAzM2YiLCJleHAiOjE3MzYxODA4NDUsImlzcyI6IkNvc3RDcmFmdCIsImF1ZCI6IkNvc3RDcmFmdCJ9.ETH2gwSvkUeGkhL0VoR1A7veRLfkC4jAbAMxf3AYzIo

POST {{CostCraft.Api_HostAddress}}/users/{{UserId}}/products
Content-Type: application/json
Authorization: Bearer {{Token}}

{
  	"name": "Cake",
	"unitsProduced": 1,
	"profitMarginPercentage": 200,
	"materials": [
		{
			"name": "Flour",
			"purchasedAmount": 1,
			"purchasedUnit": "Kilogram",
			"purchasedPrice": 2.00,
			"usedAmount": 0.25,
			"usedUnit": "Kilogram",
			"usedCost": 0.50
		}
	],
	"labors": [
		{
			"timeUnit": "Hour",
			"timePayRate": 10.00,
			"timeWorked": 2,
			"timeCost": 20.00
		}
	]
}

###
