@CostCraft.Api_HostAddress = https://localhost:7287

POST {{CostCraft.Api_HostAddress}}/auth/login
Content-Type: application/json

{
  "userName": "mr-sergito",
  "password": "mr-sergito123"
}

###

POST {{CostCraft.Api_HostAddress}}/auth/login
Content-Type: application/json

{
  "userName": "mr-sergitoo",
  "password": "mr-sergito123"
}

###

POST {{CostCraft.Api_HostAddress}}/auth/login
Content-Type: application/json

{
  "userName": "mr-sergito",
  "password": "mr-sergito1234"
}

###
