@CostCraft.Api_HostAddress = https://localhost:7287

POST {{CostCraft.Api_HostAddress}}/auth/register
Content-Type: application/json

{
  "username": "mr-sergito",
  "password": "mr-sergito123",
  "preferredCurrency": "EUR"
}

###

POST {{CostCraft.Api_HostAddress}}/auth/register
Content-Type: application/json

{
  "username": "",
  "password": "",
  "preferredCurrency": ""
}

###

POST {{CostCraft.Api_HostAddress}}/auth/register
Content-Type: application/json

{
  "username": "mr-sergito",
  "password": null,
  "preferredCurrency": "EUR"
}

###
